//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login.wsLogin {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsLogin.loginSoap")]
    public interface loginSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento _Usuario del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        Login.wsLogin.LoginResponse Login(Login.wsLogin.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<Login.wsLogin.LoginResponse> LoginAsync(Login.wsLogin.LoginRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public Login.wsLogin.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(Login.wsLogin.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string _Usuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string _Contrasena;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string _Usuario, string _Contrasena) {
            this._Usuario = _Usuario;
            this._Contrasena = _Contrasena;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Login.wsLogin.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(Login.wsLogin.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Login.wsLogin.ArrayOfString LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(Login.wsLogin.ArrayOfString LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface loginSoapChannel : Login.wsLogin.loginSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class loginSoapClient : System.ServiceModel.ClientBase<Login.wsLogin.loginSoap>, Login.wsLogin.loginSoap {
        
        public loginSoapClient() {
        }
        
        public loginSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public loginSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public loginSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public loginSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Login.wsLogin.LoginResponse Login.wsLogin.loginSoap.Login(Login.wsLogin.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public Login.wsLogin.ArrayOfString Login(string _Usuario, string _Contrasena) {
            Login.wsLogin.LoginRequest inValue = new Login.wsLogin.LoginRequest();
            inValue.Body = new Login.wsLogin.LoginRequestBody();
            inValue.Body._Usuario = _Usuario;
            inValue.Body._Contrasena = _Contrasena;
            Login.wsLogin.LoginResponse retVal = ((Login.wsLogin.loginSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Login.wsLogin.LoginResponse> Login.wsLogin.loginSoap.LoginAsync(Login.wsLogin.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Login.wsLogin.LoginResponse> LoginAsync(string _Usuario, string _Contrasena) {
            Login.wsLogin.LoginRequest inValue = new Login.wsLogin.LoginRequest();
            inValue.Body = new Login.wsLogin.LoginRequestBody();
            inValue.Body._Usuario = _Usuario;
            inValue.Body._Contrasena = _Contrasena;
            return ((Login.wsLogin.loginSoap)(this)).LoginAsync(inValue);
        }
    }
}
